# Generated by Django 4.2.15 on 2026-08-19 04:38

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Budget amount must be greater than 0.')])),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Month must be between 1 and 12.'), django.core.validators.MaxValueValidator(12, message='Month must be between 1 and 12.')])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000, message='Year must be valid.'), django.core.validators.MaxValueValidator(2100, message='Year must be valid.')])),
                ('alert_percentage', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'db_table': 'budgets',
                'ordering': ['-year', '-month', 'category__name'],
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='budgets_user_id_06b980_idx'), models.Index(fields=['user', 'category'], name='budgets_user_id_db14cc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'month', 'year'), name='unique_user_category_month_year_budget'),
        ),
    ]
