# Generated by Django 4.2.15 on 2026-08-19 04:38

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Amount must be greater than 0.')])),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Debit/Credit Card'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('WALLET', 'Digital Wallet'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
                'db_table': 'income',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='income_user_id_1e06fe_idx'), models.Index(fields=['user', 'category'], name='income_user_id_d7abfb_idx'), models.Index(fields=['user', 'is_deleted'], name='income_user_id_77f3d7_idx')],
            },
        ),
    ]
